--- 
title: "Radon mapping with R"
author: "Javier Elío"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [library.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Radon mapping concepts with examples"
---

```{r setup, include=FALSE}
# Chunk options 
  knitr::opts_chunk$set(include = TRUE,
                        echo = TRUE,
                        fig.pos = "H",
                        fig.align = "center",
                        warning = FALSE,
                        message = FALSE,
                        comment = "#>")
  options(knitr.kable.NA = "-")
  
```

# Prerequisites {-}

The data have been analysed with **R** (version `r paste(R.Version()$major, R.Version()$minor, sep = ".")`) and **Rstudio** (versio `r rstudioapi::versionInfo()$version`), and the book has been created with **bookdown** package. The required packages are automatically checked and installed if needed from CRAN.

```{r, results='hide'}

# Create an auxiliary function for checking if a package is installed,
# install it if it is not, and load the package
# (based on https://gist.github.com/stevenworthington/3178163) 
  ipak <- function(pkg){
    new_pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new_pkg)) 
      install.packages(new_pkg,
                       dependencies = TRUE,
                       repos = "http://cran.us.r-project.org")
    sapply(pkg, require, character.only = TRUE)
  }
  # List of packages 
  pkg <- c("tidyverse",
           "sf", 
           "sp", 
           "gstat"
           )
  # Check and install
  ipak(pkg)
  
```

```{r}

# You may also need to install the following packages

  #install.packages(c("MASS", "StatDA", "NADA", "truncnorm", "units", "leaflet", "ggspatial", "gridExtra", "rgdal"))

```

```{r, include=FALSE}

# automatically create a bib database for R packages
knitr::write_bib(x = c(.packages()), file = 'packages.bib')

```

## R session {-}

```{r R-session, echo = FALSE}
sessionInfo()
```
